---
title: "ewce_analysis"
author: "Aydan Askarova"
date: "13/11/2024"
output: html_document
---


```{r setup, include=FALSE}
library(qs)
library(Seurat)
library(SingleCellExperiment)
library(EWCE)
library(data.table)
library(pheatmap)
library(dplyr)
library(ggplot2)
```


##Looking at cell specificity of promoter annotated genes 
```{r}
load("~/../projects/epinott/live/user_analysed_data/Aydan/vasculature_disease_epi/sc_tsartsalis/ctd/sc_tsartsalis2024_sc_tsartsalis.rda")

cell=c("pu1VSall",  "olig2VSall", "ergVSall", "notch3VSall", "neunVSall", "rfx4VSall",  "endo_ipsc_acVSall", "peri_ipsc_acVSall", "peri_prim_acVSall")

fdr<-c(0.01)
ID<-c("ADvas_AAA_20240918_k4me3_hg19")

annotType<-c("cluster_celltype_paper" = 1) #, "cluster_celltype_pipeline"=2, "cluster_celltype"=3
annotLevel<-c(1)

for(c in 1:length(cell)){
  for(type in names(annotType)) {
    for(f in 1:length(fdr)) {
genes<-fread(input = paste0("~/../projects/epinott/live/user_analysed_data/Aydan/vasculature_disease_epi/promoters_enhancers/", ID, "/chipseeker_genes_inVivo_inVitro/", ID, ".", cell[c], ".", fdr[f],  ".promoters.txt"))

reps <- 100000
annotLevel <- annotType[type]

print(paste("Running for type:", type, "with annotLevel:", annotLevel, "for cell type:", cell[c]))
full_results <- EWCE::bootstrap_enrichment_test(sct_data = ctd,
                                                sctSpecies = "human",
                                                genelistSpecies = "human",
                                                hits = unique(genes$SYMBOL), 
                                                reps = reps,
                                                annotLevel = annotLevel)


results<-full_results$results
fwrite(x = results, file = paste0("~/../projects/epinott/live/user_analysed_data/Aydan/vasculature_disease_epi/sc_tsartsalis/ewce/", ID, "/", cell[c], ".deg.", annotLevel, ".", "inVivo_inVitro.sc_tsartsalis2024.txt"), sep = "\t", col.names = T, row.names = F)
  }}}


```

##Uploading the ewce data 
```{r}

cell=c("pu1VSall",  "olig2VSall", "ergVSall", "notch3VSall", "neunVSall", "rfx4VSall", "peri_prim_acVSall", "endo_ipsc_acVSall", "peri_ipsc_acVSall")
fdr<-c(0.01)
ID<-c("ADvas_AAA_20240918_k4me3_hg19")
annotType<-c("cluster_celltype_paper" = 1)
annotLevel<-c(1:3)

std<-data.frame(CellType=ewce_full$CellType)
pvalue<-data.frame(CellType=ewce_full$CellType)
for(c in 1:length(cell)){
  for(type in names(annotType)) {
ewce_full<-fread(input = paste0("~/../projects/epinott/live/user_analysed_data/Aydan/vasculature_disease_epi/sc_tsartsalis/ewce/",ID, "/", cell[c], ".deg.", annotType, ".", "inVivo_inVitro.sc_tsartsalis2024.txt"))

results<-ewce_full[,c(1,5)]
#results$sd_from_mean<-ifelse(results$sd_from_mean < 0, 0, results$sd_from_mean)
significant<-ewce_full[,c(1,6)]
significant$q <- ifelse(significant$q == 0, "**",
                      ifelse(significant$q < 0.05, "*", ""))

colnames(results)<-c("CellType", paste0(cell[c]))
colnames(significant)<-c("CellType", paste0(cell[c]))

std<-merge(std, results, by="CellType")
pvalue<-merge(pvalue, significant, by="CellType")
  }
}
rownames(std)<-std$CellType
std<-std[,-1]
rownames(pvalue)<-pvalue$CellType
pvalue<-pvalue[,-1]

```

##Ewce visualising 
```{r}

color_palette <- colorRampPalette(colors = c("#FFFFFF", "#EAFDB4", "#C5E862", "#6DC335", "#117733"))(100)
#color_palette <- colorRampPalette(colors = c("#FFFFFF","#C5E862","#6DC335", "#117733"))(1000)

rownames(std)<-c("ASTROCYTES", "BEC", "FIBROBLASTS", "LYMPHOCYTES", "MICROGLIA", "NEURONS", "OLIGODENDROCYTES", "SMC/PERICYTES")
std<-std[c("MICROGLIA", "LYMPHOCYTES", "BEC", "FIBROBLASTS", "SMC/PERICYTES", "ASTROCYTES", "NEURONS", "OLIGODENDROCYTES"),]

colnames(std)<-c("pu1", "olig2", "erg", "notch3", "neun", "rfx4", "peri_prim_ac", "endo_ipsc_ac", "peri_ipsc_ac")
std<-std[,c("pu1", "erg", "notch3", "rfx4", "neun", "olig2", "endo_ipsc_ac", "peri_ipsc_ac",  "peri_prim_ac")]

rownames(pvalue)<-c("ASTROCYTES", "BEC", "FIBROBLASTS", "LYMPHOCYTES", "MICROGLIA", "NEURONS", "OLIGODENDROCYTES", "SMC/PERICYTES")
pvalue<-pvalue[c("MICROGLIA", "LYMPHOCYTES", "BEC", "FIBROBLASTS", "SMC/PERICYTES", "ASTROCYTES", "NEURONS", "OLIGODENDROCYTES"),]

colnames(pvalue)<-c("pu1", "olig2", "erg", "notch3", "neun", "rfx4", "peri_prim_ac", "endo_ipsc_ac", "peri_ipsc_ac")
pvalue<-pvalue[,c("pu1", "erg", "notch3", "rfx4", "neun", "olig2", "endo_ipsc_ac", "peri_ipsc_ac",  "peri_prim_ac")]

annotation_col<-data.frame(CellType=colnames(std))
rownames(annotation_col)<-annotation_col$CellType

annotation_color<-list(CellType=c("pu1" = "#BC3934", "pu1_tf" = "#EA4545", "erg"="#785594", "erg_tf"="#DBB7F5", "notch3"="#5F2828", "olig2_tf"="#9ADEFE",  "olig2"="#0072B2", "rfx4"="#E69F00", "neun"="#009E73", "endo_ipsc_ac" ="#E852C1", "peri_ipsc_ac"="#927D04", "peri_prim_ac"="#7D626C"))

std[std < 0] <- 0

pheatmap(mat = std, annotation_col = annotation_col, annotation_colors = annotation_color, show_colnames = F,
         gaps_col = c(6,9),
         color = color_palette, 
         display_numbers = pvalue, 
         cluster_rows = F, 
         cluster_cols = F, 
         treeheight_row = F, 
         treeheight_col = F, 
         angle_col = 90, 
         fontsize_number = 12,
         fontsize = 7, cellwidth = 30, cellheight = 30, height = 5, width = 9, 
         filename = paste0("~/../projects/epinott/live/user_analysed_data/Aydan/vasculature_disease_epi/sc_tsartsalis/graphs/ADvas_AAA_20240422_ac_k4me3_inVivo_inVitro.hg19.deg.", annotType[type], ".pdf"))
```
